
''' VARIAVÉIS '''

MAX_NOTICIAS = 10 # ALTERE AQUI PARA CAPTURAR MAIS NOTICIAS DO FEED RSS
BUFFER_SIZE01 = 512 
SERVER_CLIENT = 'localhost'
SERVER = '0.0.0.0'
PORT = 5678 # ALTERE AQUI PARA MUDAR A PORTA DO SEU SERVIDOR
PROMPT = 'Digite > ' # ALTERE AQUI PARA MUDAR O PROMPT DO CLIENTE
UNICODE = 'utf-8'
BUFFER = 4096 